apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: icjqoj097-python 
  janus-idp.io/tekton: icjqoj097-python
  backstage.io/kubernetes-id: icjqoj097-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: icjqoj097-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  